### ISSUE TITLE
No output on TD

### ISSUE THREAD

**Issue by michael-hirschmugl** [delsauce/ArduinoDueHiFi#3]
I have a little problem when using this library. I have a WM8731 set up for I2S, it's producing a BCLK, TF and RF and also it produces (obviously) random chunks of data on the RD line. I checked that with an oscilloscope. I am running your example code for sine wave output, but the TD line does not output anything from the arduino due.
So now I am trying to debug my code and I have a few quick questions for you that I can't answer myself.
1. Regarding the setup of your library, does the TD line only provide a signal if it gets a proper TF and BCLK or is it always putting out something even if it's not synced? The clock signals look a bit "grungy" and I am wondering if I NEED to even them out anyway before trying something else?
2. I feed the Codec with a clock signal from the Arduino Due. This signal is a 12MHz signal which lets the Codec communicate and work correctly. My question is, I use the following code to produce this signal:
REG_PIOA_WPMR = 0x50494F00;  // enable writes
REG_PIOA_PDR |= 0x02;        // enable peripheral control
REG_PIOA_PER &= ~0x02;        // Prevents disabling peripheral control of the pin
REG_PIOA_ABSR |= 0x02;       // B preipherial select
REG_PIOA_WPMR = 0x50494F01;  // disable writes
REG_PMC_WPMR = 0x504D4300;   // enable writes
REG_PMC_SCER |= 0x100;
PMC->PMC_PCK[0] = 0b00000000000000000000000000000001;       // master clock = 12Mhz (crystal freq)
Since I cannot tell all the dependencies of the SAM processor, do you have any idea if this code might prevent the SSC interface from working correctly?

The problem is: If I remoce the code that generates the Clock signal for the Codec to see if it prevents the CCS from working, I will not have a BCLK or TF signal on the arduino due, and then I can't say where the problem really is. :)
I really hope that you can help me out!!

**Comment by sriranjanr** [comment]
Hello Hirschmensch,

Can you please post your code. I am trying to get the WM8731 to work with the Due using this library but I am not getting any output on the head phones.

**Comment by sriranjanr** [comment]
Here is my modified code based on the passthrough example.
#include <HiFi.h>
#include <Wire.h>
#define LINVOL 23
#define RINVOL 23
#define LHPVOL 100
#define RHPVOL 100
#define ADCHPD 0
#define SIDEATT 0
#define SIDETONE 0
#define DACSEL 1
#define BYPASS 0
#define INSEL 0
#define MUTEMIC 1
#define MICBOOST 0
#define SAMPLE_RATE 44

void codecTxReadyInterrupt(HiFiChannelID_t);
void codecRxReadyInterrupt(HiFiChannelID_t);

static uint32_t ldat = 0;
static uint32_t rdat = 0;


void AudioCodec_init() {
       
        int temp_wire1;
        int temp_wire2;
       
        Wire.begin();
        Wire.beginTransmission(0x1a);
        Wire.write(0x0c); // power reduction register
        Wire.write((uint8_t)0x00); // turn everything on
        temp_wire1 = Wire.endTransmission();
       
        Wire.beginTransmission(0x1a);
        Wire.write(0x0e); // digital data format
        //Wire.write(0x03); // 16b SPI mode
        Wire.write(0x02);
        temp_wire2 = Wire.endTransmission();
       
        Serial.println(temp_wire1);
        Serial.println(temp_wire2);
       
        Wire.beginTransmission(0x1a);
        Wire.write((uint8_t)0x00); // left in setup register
        Wire.write((uint8_t)LINVOL);
        Wire.endTransmission();
       
        Wire.beginTransmission(0x1a);
        Wire.write(0x02); // right in setup register
        Wire.write((uint8_t)RINVOL);
        Wire.endTransmission();
       
        Wire.beginTransmission(0x1a);
        Wire.write(0x04); // left headphone out register
        Wire.write((uint8_t)LHPVOL);
        Wire.endTransmission();
       
        Wire.beginTransmission(0x1a);
        Wire.write(0x06); // right headphone out register
        Wire.write((uint8_t)RHPVOL);
        Wire.endTransmission();
       
        Wire.beginTransmission(0x1a);
        Wire.write(0x0a); // digital audio path configuration
        Wire.write((uint8_t)ADCHPD);
        Wire.endTransmission();
       
        Wire.beginTransmission(0x1a);
        Wire.write(0x08); // analog audio pathway configuration
        Wire.write((uint8_t)((SIDEATT << 6)|(SIDETONE << 5)|(DACSEL << 4)|(BYPASS << 3)|(INSEL << 2)|(MUTEMIC << 1)|(MICBOOST << 0)));
        Wire.endTransmission();
       
        Wire.beginTransmission(0x1a);
        Wire.write(0x10); // clock configuration
        #if SAMPLE_RATE == 88
          Wire.write(0xbc);
        #elif SAMPLE_RATE == 44
          Wire.write(0xa0);
        #elif SAMPLE_RATE == 22
          Wire.write(0xe0);
        #elif SAMPLE_RATE == 8
          Wire.write(0xac);
        #elif SAMPLE_RATE == 2
          Wire.write(0xce);
        #endif
        Wire.endTransmission();
     
        Wire.beginTransmission(0x1a);
        Wire.write(0x12); // codec enable
        Wire.write(0x01);
        Wire.endTransmission();
       
}


void setup() {
 
  // set codec into reset
  pinMode(7, OUTPUT);
  digitalWrite(7, LOW);
  Serial.begin(38400);
  AudioCodec_init();
  delay(2000);
  HiFi.begin();
 
  // Configure transmitter for 2 channels, external TK/TF clocks, 32 bit per
  // channel (data less than 32-bit is left justified in the 32 bit word, but
  // codec config needs 32 clocks per channel).
  HiFi.configureTx(HIFI_AUDIO_MODE_STEREO, HIFI_CLK_MODE_USE_EXT_CLKS, 32);
 
  // Same config as above, except sync the receiver to transmitter (RK/RF
  // clock signals not needed)
  HiFi.configureRx(HIFI_AUDIO_MODE_STEREO, HIFI_CLK_MODE_USE_TK_RK_CLK, 32);

  // Since we've decided to sync the receiver to the transmitter, we could 
  // handle both reading and writing in a single interrupt (receive or 
  // transmit).  This example uses both just for demonstration purposes.
  HiFi.onTxReady(codecTxReadyInterrupt);
  HiFi.onRxReady(codecRxReadyInterrupt);
 
  // release codec from reset
  digitalWrite(7, HIGH);
 
  // Enable both receiver and transmitter.
  HiFi.enableRx(true);
  HiFi.enableTx(true);
}

void loop() {

Serial.print(ldat);
Serial.print(" ");
Serial.println(rdat);

}



void codecTxReadyInterrupt(HiFiChannelID_t channel)
{
  if (channel == HIFI_CHANNEL_ID_1)
  {
    // Left channel
    HiFi.write(ldat);  
  }
  else
  {
    // Right channel
    HiFi.write(rdat);
  }
}

void codecRxReadyInterrupt(HiFiChannelID_t channel)
{
  if (channel == HIFI_CHANNEL_ID_1)
  {
    // Left channel
    ldat = HiFi.read();
  }
  else
  {
    // Right channel
    rdat = HiFi.read();
  }
}

**Comment by hirschmensch** [comment]
hey sorry for the late response.
i'm afraid with the WM8731 it's not that easy. :/
but i will provide a dedicated library soon and keep you posted!

**Comment by benbiles** [comment]
Hi sriranjanr,

Heres some code using some of your initialisation setup thats working with Passthough example.
I changed to 32 bit and 48khz

`
// include 2wire ( i2c ) 
#include <Wire.h>

// WM8731 setup

#define LINVOL 20
#define RINVOL 20
#define LHPVOL 127
#define RHPVOL 127
#define ADCHPD 0
#define SIDEATT 0
#define SIDETONE 0
#define DACSEL 1
#define BYPASS 0
#define INSEL 1
#define MUTEMIC 0
#define MICBOOST 1
#define SAMPLE_RATE 48


// I2S IO library

#include <HiFi.h>

void codecTxReadyInterrupt(HiFiChannelID_t);
void codecRxReadyInterrupt(HiFiChannelID_t);

static uint32_t ldat = 0;
static uint32_t rdat = 0;

void setup() {

Serial.begin(9600);

Serial.println( "Initializing" );
delay(100);

// Initialize the WM8731


    Wire.begin();
    Wire.beginTransmission(0x1a);
    Wire.write(0x0c); // power reduction register
    Wire.write((uint8_t)0x00); // turn everything on
    Wire.endTransmission();

    delay(200);

    Wire.beginTransmission(0x1a);
    Wire.write(0x07); // digital data format REG 0000111   0x7
    Wire.write(0xB2);  // 32bit,MASTER MODE  10110010 
    Wire.endTransmission();

    delay(200);

    Wire.beginTransmission(0x1a);
    Wire.write((uint8_t)0x00); // left in setup register
    Wire.write((uint8_t)LINVOL);
    Wire.endTransmission();

    delay(200);

    Wire.beginTransmission(0x1a);
    Wire.write(0x02); // right in setup register
    Wire.write((uint8_t)RINVOL);
    Wire.endTransmission();

    delay(200);

    Wire.beginTransmission(0x1a);
    Wire.write(0x04); // left headphone out register
    Wire.write((uint8_t)LHPVOL);
    Wire.endTransmission();

    delay(200);

    Wire.beginTransmission(0x1a);
    Wire.write(0x06); // right headphone out register
    Wire.write((uint8_t)RHPVOL);
    Wire.endTransmission();

    delay(200);

    Wire.beginTransmission(0x1a);
    Wire.write(0x0a); // digital audio path configuration
    Wire.write((uint8_t)ADCHPD);
    Wire.endTransmission();

    delay(200);

    Wire.beginTransmission(0x1a);
    Wire.write(0x08); // analog audio pathway configuration
    Wire.write((uint8_t)((SIDEATT << 6)|(SIDETONE << 5)|(DACSEL << 4)|(BYPASS << 3)|(INSEL << 2)|(MUTEMIC << 1)|(MICBOOST << 0)));
    Wire.endTransmission();

    delay(200);

    Wire.beginTransmission(0x1a);
    Wire.write(0x10); // clock configuration
    #if SAMPLE_RATE == 88
      Wire.write(0xbc);
    #elif SAMPLE_RATE == 48
      Wire.write(0x00);  
    #elif SAMPLE_RATE == 44
      Wire.write(0xa0);
    #elif SAMPLE_RATE == 22
      Wire.write(0xe0);
    #elif SAMPLE_RATE == 8
      Wire.write(0xac);
    #elif SAMPLE_RATE == 2
      Wire.write(0xce);
    #endif
    Wire.endTransmission();

    delay(200);

    Wire.beginTransmission(0x1a);
    Wire.write(0x12); // codec enable
    Wire.write(0x01);
    Wire.endTransmission();

    delay(200);

  Serial.println( "done" );
  delay(1000);

  
  // Initialize the Arduino SSC codec ? 
 
  // set SSC DUE I2S codec into reset
  pinMode(7, OUTPUT);
  digitalWrite(7, LOW);
 
  HiFi.begin();
 
  // Configure transmitter for 2 channels, external TK/TF clocks, 32 bit per
  // channel (data less than 32-bit is left justified in the 32 bit word, but
  // codec config needs 32 clocks per channel).
  HiFi.configureTx(HIFI_AUDIO_MODE_STEREO, HIFI_CLK_MODE_USE_EXT_CLKS, 32);
 
  // Same config as above, except sync the receiver to transmitter (RK/RF
  // clock signals not needed)
  HiFi.configureRx(HIFI_AUDIO_MODE_STEREO, HIFI_CLK_MODE_USE_TK_RK_CLK, 32);

  // Since we've decided to sync the receiver to the transmitter, we could 
  // handle both reading and writing in a single interrupt (receive or 
  // transmit).  This example uses both just for demonstration purposes.
  HiFi.onTxReady(codecTxReadyInterrupt);
  HiFi.onRxReady(codecRxReadyInterrupt);
 
  // release codec from reset
  digitalWrite(7, HIGH);
 
  // Enable both receiver and transmitter.
  HiFi.enableRx(true);
  HiFi.enableTx(true);
}

void loop() {

    if (ldat > 0 & rdat > 0 ) Serial.print(ldat,rdat);
    if (ldat > 0 & rdat > 0 ) Serial.println();
 
  }

  

void codecTxReadyInterrupt(HiFiChannelID_t channel)
{
  if (channel == HIFI_CHANNEL_ID_1)
  {
    // Left channel
    HiFi.write(ldat);  
  }
  else
  {
    // Right channel
    HiFi.write(rdat);
  }
}

void codecRxReadyInterrupt(HiFiChannelID_t channel)
{
  if (channel == HIFI_CHANNEL_ID_1)
  {
    // Left channel
    ldat = HiFi.read();
  }
  else
  {
    // Right channel
    rdat = HiFi.read();
  }
}
`
